#!/usr/bin/env bash
# gen-nephos-acl.sh — generate the Tailscale ACL from roles/ and hosts/layers.conf.
#
# This is the real enforcement boundary for the tier model. The control plane is
# reached over HTTP on the tailnet, so "can this machine provision" is decided by
# whether it can open that port — not by anything in this repo, and not by the
# SSH restriction, which only covers a second path.
#
# Generated rather than hand-written so a role change cannot silently fail to
# reach the thing that enforces it.
#
#   ./scripts/gen-nephos-acl.sh            print the policy
#   ./scripts/gen-nephos-acl.sh --check    verify it matches the roles (exit 1 if not)
set -uo pipefail

DOTFILES="$(cd "$(dirname "$0")/.." && pwd)"
export DOTFILES
. "$DOTFILES/lib/roles.sh"

CONTROL_PORT="${NEPHOS_CONTROL_PORT:-7930}"

allow_tags=()
deny_tags=()
for role in $(all_roles); do
  case "$(role_get "$role" control_port)" in
    allow) allow_tags+=("tag:$role") ;;
    deny)  deny_tags+=("tag:$role") ;;
  esac
done

join() { local IFS=", "; printf '%s' "$*"; }
quote_all() { local t out=(); for t in "$@"; do out+=("\"$t\""); done; join "${out[@]}"; }

cat <<EOF
// GENERATED by scripts/gen-nephos-acl.sh from roles/*.role and hosts/layers.conf.
// Do not hand-edit — regenerate instead, or the roles and the boundary drift.
//
// THIS IS A COMPLETE POLICY AND REPLACES YOUR CURRENT ONE. Tailscale ACLs are
// allow-only and have no "except", so denying the nodes the control API means
// enumerating every other port they legitimately need. A port missing from a
// role's service_ports is a service that silently stops working for every
// worker — and a mistake here can lock every machine out of the tailnet,
// including the ssh used to fix it.
//
// USE THE ADMIN CONSOLE'S PREVIEW/TEST BEFORE SAVING.
//
// Tag each machine to match its declared role:
EOF

for role in $(all_roles); do
  hosts=""
  for h in $(hosts_with_role "$role"); do hosts="$hosts $h"; done
  printf '//   tag:%-18s%s\n' "$role" "${hosts:-  (no hosts)}"
done

cat <<EOF
// The control plane host must also carry tag:nephos-control.

{
  "tagOwners": {
$(for role in $(all_roles); do printf '    "tag:%s": ["autogroup:admin"],\n' "$role"; done)
    "tag:nephos-control": ["autogroup:admin"]
  },

  "acls": [
EOF

for role in $(all_roles); do
  ports="$(role_get "$role" service_ports)"
  cp="$(role_get "$role" control_port)"
  echo "    // $role — $(role_get "$role" summary)"
  if [ "$cp" = "allow" ] && [ "$ports" = "*" ]; then
    cat <<EOF
    { "action": "accept", "src": ["tag:$role"], "dst": ["*:*"] },

EOF
  else
    cat <<EOF
    // control API ($CONTROL_PORT) is deliberately absent from this list.
    { "action": "accept", "src": ["tag:$role"], "dst": ["tag:nephos-control:$ports"] },
    // peer traffic between workers stays open.
    { "action": "accept", "src": ["tag:$role"], "dst": ["tag:$role:*"] },

EOF
  fi
done

cat <<EOF
    // Everything reaches the public gateway ports.
    { "action": "accept", "src": ["*"], "dst": ["tag:nephos-control:80,443"] }
  ],

  "ssh": [
    // Interactive ssh from the humans' machines.
    {
      "action": "check",
      "src": [$(quote_all "${allow_tags[@]}")],
      "dst": ["tag:nephos-control", "tag:nephos-node"],
      "users": ["autogroup:nonroot"]
    }
  ]
}
EOF

if [ "${1:-}" = "--check" ]; then
  # A role that may provision but cannot reach the control port is incoherent —
  # it would be granted an ability it structurally cannot exercise.
  bad=0
  for role in $(all_roles); do
    if role_may "$role" provision && [ "$(role_get "$role" control_port)" = "deny" ]; then
      echo "INCOHERENT: $role may 'provision' but control_port is 'deny'" >&2
      bad=1
    fi
    if ! role_may "$role" provision && [ "$(role_get "$role" control_port)" = "allow" ]; then
      echo "WARN: $role cannot provision yet reaches the control port" >&2
    fi
  done
  exit "$bad"
fi
