#!/usr/bin/env bash
# gen-nephos-acl.sh — generate the Tailscale ACL from roles/ and hosts/layers.conf.
#
# This is the real enforcement boundary for the tier model. The control plane is
# reached over HTTP on the tailnet, so "can this machine provision" is decided by
# whether it can open that port — not by anything in this repo, and not by the
# SSH restriction, which only covers a second path.
#
# Generated rather than hand-written so a role change cannot silently fail to
# reach the thing that enforces it.
#
#   ./scripts/gen-nephos-acl.sh            print the policy
#   ./scripts/gen-nephos-acl.sh --check    verify it matches the roles (exit 1 if not)
set -uo pipefail

DOTFILES="$(cd "$(dirname "$0")/.." && pwd)"
export DOTFILES
. "$DOTFILES/lib/roles.sh"

CONTROL_PORT="${NEPHOS_CONTROL_PORT:-7930}"

allow_tags=()
deny_tags=()
for role in $(all_roles); do
  case "$(role_get "$role" control_port)" in
    allow) allow_tags+=("tag:$role") ;;
    deny)  deny_tags+=("tag:$role") ;;
  esac
done

join() { local IFS=", "; printf '%s' "$*"; }
quote_all() { local t out=(); for t in "$@"; do out+=("\"$t\""); done; join "${out[@]}"; }

cat <<EOF
// GENERATED by scripts/gen-nephos-acl.sh from roles/*.role and hosts/layers.conf.
// Do not hand-edit — regenerate instead, or the roles and the boundary drift.
//
// Tag each machine in the Tailscale admin console to match its declared role:
EOF

for role in $(all_roles); do
  hosts=""
  for r in $(all_roles); do :; done
  for h in $(hosts_with_role "$role"); do hosts="$hosts $h"; done
  printf '//   tag:%-18s%s\n' "$role" "${hosts:-  (no hosts)}"
done

cat <<EOF
// The control plane itself must carry tag:nephos-control.

{
  "tagOwners": {
$(for role in $(all_roles); do printf '    "tag:%s": ["autogroup:admin"],\n' "$role"; done)
    "tag:nephos-control": ["autogroup:admin"]
  },

  "acls": [
    // Roles whose control_port is 'allow' reach the control API.
    {
      "action": "accept",
      "src": [$(quote_all "${allow_tags[@]}")],
      "dst": ["tag:nephos-control:$CONTROL_PORT"]
    },

    // Roles whose control_port is 'deny' get NO rule granting that port.
    // Tailscale denies by default, so the absence IS the denial:
    //   $(quote_all "${deny_tags[@]}")
    //
    // They still reach inference and storage, which is the point of a worker.
    {
      "action": "accept",
      "src": [$(quote_all "${deny_tags[@]}")],
      "dst": ["tag:nephos-control:443", "tag:nephos-control:80"]
    }
  ],

  "ssh": [
    // Interactive SSH for the humans' machines only.
    {
      "action": "check",
      "src": [$(quote_all "${allow_tags[@]}")],
      "dst": ["tag:nephos-control"],
      "users": ["autogroup:nonroot"]
    }
  ]
}
EOF

if [ "${1:-}" = "--check" ]; then
  # A role that may provision but cannot reach the control port is incoherent —
  # it would be granted an ability it structurally cannot exercise.
  bad=0
  for role in $(all_roles); do
    if role_may "$role" provision && [ "$(role_get "$role" control_port)" = "deny" ]; then
      echo "INCOHERENT: $role may 'provision' but control_port is 'deny'" >&2
      bad=1
    fi
    if ! role_may "$role" provision && [ "$(role_get "$role" control_port)" = "allow" ]; then
      echo "WARN: $role cannot provision yet reaches the control port" >&2
    fi
  done
  exit "$bad"
fi
