#!/usr/bin/env bash
# layers: nephos-keeper nephos-operator
#
# Regenerate ~/.ssh/config.d/fleet from hosts/fleet.conf.
#
# WHY THIS EXISTS: scripts/fleet.sh addresses every machine by ssh alias, and
# those aliases lived only in ~/.ssh/config — untracked, on one Mac. Rebuild that
# Mac and `make fleet` stops working, with nothing in the repo saying what the
# aliases were. The mapping is now tracked; this turns it back into ssh config.
#
# Written to a separate file that ~/.ssh/config Includes, so hand-written entries
# (work hosts, one-off boxes, jump configs) are never touched. Only nephos-keeper
# and nephos-operator get it — a worker node has no business addressing the fleet.
#
# Contains no secrets: MagicDNS short names resolve on-tailnet without the
# tailnet identifier, and the key path is a convention, not key material.

_fleet_conf="$DOTFILES/hosts/fleet.conf"
_ssh_dir="$HOME/.ssh"
_frag="$_ssh_dir/config.d/fleet"
_key="$HOME/.ssh/id_ed25519"

[ -f "$_fleet_conf" ] || return 0

mkdir -p "$_ssh_dir/config.d"
chmod 700 "$_ssh_dir" "$_ssh_dir/config.d" 2>/dev/null

_new="$(mktemp)"
{
  echo "# GENERATED by setup.d/30-ssh-hosts.sh from hosts/fleet.conf."
  echo "# Hand edits belong in ~/.ssh/config, which Includes this file."
  echo
  awk '!/^[[:space:]]*#/ && NF >= 4 { print $1, $3, $4 }' "$_fleet_conf" \
  | while read -r alias tsname user; do
      printf 'Host %s\n    HostName %s\n    User %s\n' "$alias" "$tsname" "$user"
      [ -f "$_key" ] && printf '    IdentityFile %s\n' "$_key"
      printf '\n'
    done
} > "$_new"

if [ -f "$_frag" ] && cmp -s "$_new" "$_frag"; then
  rm -f "$_new"
else
  mv "$_new" "$_frag"
  chmod 600 "$_frag"
  echo "    wrote $_frag ($(grep -c '^Host ' "$_frag") hosts)"
fi

# Ensure the main config pulls it in. Include must come FIRST: ssh takes the
# first value it sees for any keyword, so an Include at the bottom loses to
# anything already set above it.
if [ ! -f "$_ssh_dir/config" ]; then
  printf 'Include ~/.ssh/config.d/*\n' > "$_ssh_dir/config"
  chmod 600 "$_ssh_dir/config"
  echo "    created ~/.ssh/config with Include"
elif ! grep -q 'config.d' "$_ssh_dir/config" 2>/dev/null; then
  _tmp="$(mktemp)"
  printf 'Include ~/.ssh/config.d/*\n\n' > "$_tmp"
  cat "$_ssh_dir/config" >> "$_tmp"
  cp "$_ssh_dir/config" "$_ssh_dir/config.backup.$(date +%Y%m%d 2>/dev/null || echo bak)" 2>/dev/null
  mv "$_tmp" "$_ssh_dir/config"
  chmod 600 "$_ssh_dir/config"
  echo "    added Include to ~/.ssh/config (previous saved as config.backup.*)"
fi

unset _fleet_conf _ssh_dir _frag _key _new _tmp
